---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-np-service
  labels:
    app: bankapp-eta-app
spec:
  selector:
    app: bankapp-eta-app
  type: NodePort
  ports:
    - nodePort: 31032
      port: 8081
      targetPort: 8081
